sudo: required

language: node_js

node_js:
  - 'node'

services:
  - docker

before_install:
  - docker build -t sadorlovsky/site .

script:
  - yarn test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sadorlovsky/site;
    fi
